//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.30 at 08:33:04 AM IST 
//


package com.netapp.supportsite.domain;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProductFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Attribute">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AttrID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AttrValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SiteValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ProductLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SystemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NumberOfShelves" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="NumberOfDisks" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DispatchEngineer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ModelNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PartDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DateShipped" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="RoHSComplianceFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HardwareServiceLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LastInspectionDate" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="ASPPartnerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="OwnerCustomerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="OwnerCustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="InstalledAtSiteID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="InstalledAtSiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Secure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Addresses" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AddressCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="AddressCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AddressState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AddressZip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="AddressCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Contacts" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PartnerFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ContactFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContactUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EOSPVRFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "product",
    "eospvrFlag"
})
@XmlRootElement(name = "MT_GetIObjDetails")
public class MTGetIObjDetails {

    @XmlElement(name = "Product", required = true)
    protected MTGetIObjDetails.Product product;
    @XmlElement(name = "EOSPVRFlag", required = true)
    protected String eospvrFlag;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link MTGetIObjDetails.Product }
     *     
     */
    public MTGetIObjDetails.Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link MTGetIObjDetails.Product }
     *     
     */
    public void setProduct(MTGetIObjDetails.Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the eospvrFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEOSPVRFlag() {
        return eospvrFlag;
    }

    /**
     * Sets the value of the eospvrFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEOSPVRFlag(String value) {
        this.eospvrFlag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ProductFamily" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Attribute">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AttrID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AttrValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SiteValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ProductLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SystemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NumberOfShelves" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="NumberOfDisks" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="DispatchEngineer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ModelNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PartDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DateShipped" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="RoHSComplianceFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HardwareServiceLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LastInspectionDate" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="ASPPartnerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OwnerCustomerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OwnerCustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="InstalledAtSiteID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="InstalledAtSiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Secure" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Addresses" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AddressCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="AddressCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AddressState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AddressZip" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="AddressCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Contacts" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PartnerFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ContactFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContactUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productID",
        "productType",
        "productFamily",
        "attribute",
        "productLine",
        "systemID",
        "osVersion",
        "numberOfShelves",
        "numberOfDisks",
        "dispatchEngineer",
        "serialNumber",
        "modelNumber",
        "partDescription",
        "dateShipped",
        "roHSComplianceFlag",
        "hardwareServiceLevel",
        "lastInspectionDate",
        "aspPartnerID",
        "ownerCustomerID",
        "ownerCustomerName",
        "installedAtSiteID",
        "installedAtSiteName",
        "secure",
        "addresses",
        "contacts"
    })
    public static class Product {

        @Override
		public String toString() {
			return "Product [productID=" + productID + ", productType="
					+ productType + ", productFamily=" + productFamily
					+ ", attribute=" + attribute + ", productLine="
					+ productLine + ", systemID=" + systemID + ", osVersion="
					+ osVersion + ", numberOfShelves=" + numberOfShelves
					+ ", numberOfDisks=" + numberOfDisks
					+ ", dispatchEngineer=" + dispatchEngineer
					+ ", serialNumber=" + serialNumber + ", modelNumber="
					+ modelNumber + ", partDescription=" + partDescription
					+ ", dateShipped=" + dateShipped + ", roHSComplianceFlag="
					+ roHSComplianceFlag + ", hardwareServiceLevel="
					+ hardwareServiceLevel + ", lastInspectionDate="
					+ lastInspectionDate + ", aspPartnerID=" + aspPartnerID
					+ ", ownerCustomerID=" + ownerCustomerID
					+ ", ownerCustomerName=" + ownerCustomerName
					+ ", installedAtSiteID=" + installedAtSiteID
					+ ", installedAtSiteName=" + installedAtSiteName
					+ ", secure=" + secure + ", addresses=" + addresses
					+ ", contacts=" + contacts + "]";
		}


		@XmlElement(name = "ProductID")
        protected int productID;
        @XmlElement(name = "ProductType", required = true)
        protected String productType;
        @XmlElement(name = "ProductFamily", required = true)
        protected String productFamily;
        @XmlElement(name = "Attribute", required = true)
        protected MTGetIObjDetails.Product.Attribute attribute;
        @XmlElement(name = "ProductLine", required = true)
        protected String productLine;
        @XmlElement(name = "SystemID")
        protected int systemID;
        @XmlElement(name = "OSVersion", required = true)
        protected String osVersion;
        @XmlElement(name = "NumberOfShelves")
        protected byte numberOfShelves;
        @XmlElement(name = "NumberOfDisks")
        protected byte numberOfDisks;
        @XmlElement(name = "DispatchEngineer", required = true)
        protected String dispatchEngineer;
        @XmlElement(name = "SerialNumber")
        protected int serialNumber;
        @XmlElement(name = "ModelNumber", required = true)
        protected String modelNumber;
        @XmlElement(name = "PartDescription", required = true)
        protected String partDescription;
        @XmlElement(name = "DateShipped")
        protected int dateShipped;
        @XmlElement(name = "RoHSComplianceFlag", required = true)
        protected String roHSComplianceFlag;
        @XmlElement(name = "HardwareServiceLevel", required = true)
        protected String hardwareServiceLevel;
        @XmlElement(name = "LastInspectionDate")
        protected byte lastInspectionDate;
        @XmlElement(name = "ASPPartnerID")
        protected int aspPartnerID;
        @XmlElement(name = "OwnerCustomerID")
        protected int ownerCustomerID;
        @XmlElement(name = "OwnerCustomerName", required = true)
        protected String ownerCustomerName;
        @XmlElement(name = "InstalledAtSiteID")
        protected int installedAtSiteID;
        @XmlElement(name = "InstalledAtSiteName", required = true)
        protected String installedAtSiteName;
        @XmlElement(name = "Secure", required = true)
        protected String secure;
        @XmlElement(name = "Addresses")
        protected List<MTGetIObjDetails.Product.Addresses> addresses;
        @XmlElement(name = "Contacts")
        protected List<MTGetIObjDetails.Product.Contacts> contacts;

        /**
         * Gets the value of the productID property.
         * 
         */
        public int getProductID() {
            return productID;
        }

        /**
         * Sets the value of the productID property.
         * 
         */
        public void setProductID(int value) {
            this.productID = value;
        }

        /**
         * Gets the value of the productType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductType() {
            return productType;
        }

        /**
         * Sets the value of the productType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductType(String value) {
            this.productType = value;
        }

        /**
         * Gets the value of the productFamily property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductFamily() {
            return productFamily;
        }

        /**
         * Sets the value of the productFamily property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductFamily(String value) {
            this.productFamily = value;
        }

        /**
         * Gets the value of the attribute property.
         * 
         * @return
         *     possible object is
         *     {@link MTGetIObjDetails.Product.Attribute }
         *     
         */
        public MTGetIObjDetails.Product.Attribute getAttribute() {
            return attribute;
        }

        /**
         * Sets the value of the attribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link MTGetIObjDetails.Product.Attribute }
         *     
         */
        public void setAttribute(MTGetIObjDetails.Product.Attribute value) {
            this.attribute = value;
        }

        /**
         * Gets the value of the productLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductLine() {
            return productLine;
        }

        /**
         * Sets the value of the productLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductLine(String value) {
            this.productLine = value;
        }

        /**
         * Gets the value of the systemID property.
         * 
         */
        public int getSystemID() {
            return systemID;
        }

        /**
         * Sets the value of the systemID property.
         * 
         */
        public void setSystemID(int value) {
            this.systemID = value;
        }

        /**
         * Gets the value of the osVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOSVersion() {
            return osVersion;
        }

        /**
         * Sets the value of the osVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOSVersion(String value) {
            this.osVersion = value;
        }

        /**
         * Gets the value of the numberOfShelves property.
         * 
         */
        public byte getNumberOfShelves() {
            return numberOfShelves;
        }

        /**
         * Sets the value of the numberOfShelves property.
         * 
         */
        public void setNumberOfShelves(byte value) {
            this.numberOfShelves = value;
        }

        /**
         * Gets the value of the numberOfDisks property.
         * 
         */
        public byte getNumberOfDisks() {
            return numberOfDisks;
        }

        /**
         * Sets the value of the numberOfDisks property.
         * 
         */
        public void setNumberOfDisks(byte value) {
            this.numberOfDisks = value;
        }

        /**
         * Gets the value of the dispatchEngineer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDispatchEngineer() {
            return dispatchEngineer;
        }

        /**
         * Sets the value of the dispatchEngineer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDispatchEngineer(String value) {
            this.dispatchEngineer = value;
        }

        /**
         * Gets the value of the serialNumber property.
         * 
         */
        public int getSerialNumber() {
            return serialNumber;
        }

        /**
         * Sets the value of the serialNumber property.
         * 
         */
        public void setSerialNumber(int value) {
            this.serialNumber = value;
        }

        /**
         * Gets the value of the modelNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelNumber() {
            return modelNumber;
        }

        /**
         * Sets the value of the modelNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelNumber(String value) {
            this.modelNumber = value;
        }

        /**
         * Gets the value of the partDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartDescription() {
            return partDescription;
        }

        /**
         * Sets the value of the partDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartDescription(String value) {
            this.partDescription = value;
        }

        /**
         * Gets the value of the dateShipped property.
         * 
         */
        public int getDateShipped() {
            return dateShipped;
        }

        /**
         * Sets the value of the dateShipped property.
         * 
         */
        public void setDateShipped(int value) {
            this.dateShipped = value;
        }

        /**
         * Gets the value of the roHSComplianceFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoHSComplianceFlag() {
            return roHSComplianceFlag;
        }

        /**
         * Sets the value of the roHSComplianceFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoHSComplianceFlag(String value) {
            this.roHSComplianceFlag = value;
        }

        /**
         * Gets the value of the hardwareServiceLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHardwareServiceLevel() {
            return hardwareServiceLevel;
        }

        /**
         * Sets the value of the hardwareServiceLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHardwareServiceLevel(String value) {
            this.hardwareServiceLevel = value;
        }

        /**
         * Gets the value of the lastInspectionDate property.
         * 
         */
        public byte getLastInspectionDate() {
            return lastInspectionDate;
        }

        /**
         * Sets the value of the lastInspectionDate property.
         * 
         */
        public void setLastInspectionDate(byte value) {
            this.lastInspectionDate = value;
        }

        /**
         * Gets the value of the aspPartnerID property.
         * 
         */
        public int getASPPartnerID() {
            return aspPartnerID;
        }

        /**
         * Sets the value of the aspPartnerID property.
         * 
         */
        public void setASPPartnerID(int value) {
            this.aspPartnerID = value;
        }

        /**
         * Gets the value of the ownerCustomerID property.
         * 
         */
        public int getOwnerCustomerID() {
            return ownerCustomerID;
        }

        /**
         * Sets the value of the ownerCustomerID property.
         * 
         */
        public void setOwnerCustomerID(int value) {
            this.ownerCustomerID = value;
        }

        /**
         * Gets the value of the ownerCustomerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwnerCustomerName() {
            return ownerCustomerName;
        }

        /**
         * Sets the value of the ownerCustomerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwnerCustomerName(String value) {
            this.ownerCustomerName = value;
        }

        /**
         * Gets the value of the installedAtSiteID property.
         * 
         */
        public int getInstalledAtSiteID() {
            return installedAtSiteID;
        }

        /**
         * Sets the value of the installedAtSiteID property.
         * 
         */
        public void setInstalledAtSiteID(int value) {
            this.installedAtSiteID = value;
        }

        /**
         * Gets the value of the installedAtSiteName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstalledAtSiteName() {
            return installedAtSiteName;
        }

        /**
         * Sets the value of the installedAtSiteName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstalledAtSiteName(String value) {
            this.installedAtSiteName = value;
        }

        /**
         * Gets the value of the secure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecure() {
            return secure;
        }

        /**
         * Sets the value of the secure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecure(String value) {
            this.secure = value;
        }

        /**
         * Gets the value of the addresses property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the addresses property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddresses().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MTGetIObjDetails.Product.Addresses }
         * 
         * 
         */
        public List<MTGetIObjDetails.Product.Addresses> getAddresses() {
            if (addresses == null) {
                addresses = new ArrayList<MTGetIObjDetails.Product.Addresses>();
            }
            return this.addresses;
        }

        /**
         * Gets the value of the contacts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contacts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContacts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MTGetIObjDetails.Product.Contacts }
         * 
         * 
         */
        public List<MTGetIObjDetails.Product.Contacts> getContacts() {
            if (contacts == null) {
                contacts = new ArrayList<MTGetIObjDetails.Product.Contacts>();
            }
            return this.contacts;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AddressCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="AddressCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AddressState" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AddressZip" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="AddressCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressType",
            "addressCompany",
            "address1",
            "address2",
            "addressCity",
            "addressState",
            "addressZip",
            "addressCountry"
        })
        public static class Addresses {

            @Override
			public String toString() {
				return "Addresses [addressType=" + addressType
						+ ", addressCompany=" + addressCompany + ", address1="
						+ address1 + ", address2=" + address2
						+ ", addressCity=" + addressCity + ", addressState="
						+ addressState + ", addressZip=" + addressZip
						+ ", addressCountry=" + addressCountry + "]";
			}

			@XmlElement(name = "AddressType", required = true)
            protected String addressType;
            @XmlElement(name = "AddressCompany", required = true)
            protected String addressCompany;
            @XmlElement(name = "Address1", required = true)
            protected String address1;
            @XmlElement(name = "Address2")
            protected String address2;
            @XmlElement(name = "AddressCity", required = true)
            protected String addressCity;
            @XmlElement(name = "AddressState", required = true)
            protected String addressState;
            @XmlElement(name = "AddressZip")
            protected int addressZip;
            @XmlElement(name = "AddressCountry", required = true)
            protected String addressCountry;

            /**
             * Gets the value of the addressType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressType() {
                return addressType;
            }

            /**
             * Sets the value of the addressType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressType(String value) {
                this.addressType = value;
            }

            /**
             * Gets the value of the addressCompany property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressCompany() {
                return addressCompany;
            }

            /**
             * Sets the value of the addressCompany property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressCompany(String value) {
                this.addressCompany = value;
            }

            /**
             * Gets the value of the address1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress1() {
                return address1;
            }

            /**
             * Sets the value of the address1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress1(String value) {
                this.address1 = value;
            }

            /**
             * Gets the value of the address2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress2() {
                return address2;
            }

            /**
             * Sets the value of the address2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress2(String value) {
                this.address2 = value;
            }

            /**
             * Gets the value of the addressCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressCity() {
                return addressCity;
            }

            /**
             * Sets the value of the addressCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressCity(String value) {
                this.addressCity = value;
            }

            /**
             * Gets the value of the addressState property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressState() {
                return addressState;
            }

            /**
             * Sets the value of the addressState property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressState(String value) {
                this.addressState = value;
            }

            /**
             * Gets the value of the addressZip property.
             * 
             */
            public int getAddressZip() {
                return addressZip;
            }

            /**
             * Sets the value of the addressZip property.
             * 
             */
            public void setAddressZip(int value) {
                this.addressZip = value;
            }

            /**
             * Gets the value of the addressCountry property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressCountry() {
                return addressCountry;
            }

            /**
             * Sets the value of the addressCountry property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressCountry(String value) {
                this.addressCountry = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AttrID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AttrValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SiteValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "setType",
            "attrID",
            "attrValue",
            "siteValue"
        })
        public static class Attribute {

            @Override
			public String toString() {
				return "Attribute [setType=" + setType + ", attrID=" + attrID
						+ ", attrValue=" + attrValue + ", siteValue="
						+ siteValue + "]";
			}

			@XmlElement(name = "SetType", required = true)
            protected String setType;
            @XmlElement(name = "AttrID", required = true)
            protected String attrID;
            @XmlElement(name = "AttrValue", required = true)
            protected String attrValue;
            @XmlElement(name = "SiteValue", required = true)
            protected String siteValue;

            /**
             * Gets the value of the setType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSetType() {
                return setType;
            }

            /**
             * Sets the value of the setType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSetType(String value) {
                this.setType = value;
            }

            /**
             * Gets the value of the attrID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttrID() {
                return attrID;
            }

            /**
             * Sets the value of the attrID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttrID(String value) {
                this.attrID = value;
            }

            /**
             * Gets the value of the attrValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAttrValue() {
                return attrValue;
            }

            /**
             * Sets the value of the attrValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAttrValue(String value) {
                this.attrValue = value;
            }

            /**
             * Gets the value of the siteValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSiteValue() {
                return siteValue;
            }

            /**
             * Sets the value of the siteValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSiteValue(String value) {
                this.siteValue = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PartnerFunction" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ContactFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContactUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "partnerFunction",
            "contactID",
            "contactFirstName",
            "contactLastName",
            "contactPhone",
            "contactEmail",
            "contactUsername"
        })
        public static class Contacts {

            @Override
			public String toString() {
				return "Contacts [partnerFunction=" + partnerFunction
						+ ", contactID=" + contactID + ", contactFirstName="
						+ contactFirstName + ", contactLastName="
						+ contactLastName + ", contactPhone=" + contactPhone
						+ ", contactEmail=" + contactEmail
						+ ", contactUsername=" + contactUsername + "]";
			}

			@XmlElement(name = "PartnerFunction", required = true)
            protected String partnerFunction;
            @XmlElement(name = "ContactID")
            protected int contactID;
            @XmlElement(name = "ContactFirstName", required = true)
            protected String contactFirstName;
            @XmlElement(name = "ContactLastName", required = true)
            protected String contactLastName;
            @XmlElement(name = "ContactPhone", required = true)
            protected String contactPhone;
            @XmlElement(name = "ContactEmail", required = true)
            protected String contactEmail;
            @XmlElement(name = "ContactUsername")
            protected String contactUsername;

            /**
             * Gets the value of the partnerFunction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartnerFunction() {
                return partnerFunction;
            }

            /**
             * Sets the value of the partnerFunction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartnerFunction(String value) {
                this.partnerFunction = value;
            }

            /**
             * Gets the value of the contactID property.
             * 
             */
            public int getContactID() {
                return contactID;
            }

            /**
             * Sets the value of the contactID property.
             * 
             */
            public void setContactID(int value) {
                this.contactID = value;
            }

            /**
             * Gets the value of the contactFirstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactFirstName() {
                return contactFirstName;
            }

            /**
             * Sets the value of the contactFirstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactFirstName(String value) {
                this.contactFirstName = value;
            }

            /**
             * Gets the value of the contactLastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactLastName() {
                return contactLastName;
            }

            /**
             * Sets the value of the contactLastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactLastName(String value) {
                this.contactLastName = value;
            }

            /**
             * Gets the value of the contactPhone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactPhone() {
                return contactPhone;
            }

            /**
             * Sets the value of the contactPhone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactPhone(String value) {
                this.contactPhone = value;
            }

            /**
             * Gets the value of the contactEmail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactEmail() {
                return contactEmail;
            }

            /**
             * Sets the value of the contactEmail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactEmail(String value) {
                this.contactEmail = value;
            }

            /**
             * Gets the value of the contactUsername property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContactUsername() {
                return contactUsername;
            }

            /**
             * Sets the value of the contactUsername property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContactUsername(String value) {
                this.contactUsername = value;
            }

        }

    }


	@Override
	public String toString() {
		return "MTGetIObjDetails [product=" + product + ", eospvrFlag="
				+ eospvrFlag + "]";
	}

}
